declare module '@nlpjs/basic' {
  import { ConsoleConnector } from '@nlpjs/console-connector'
  import {
    Among,
    ArrToObj,
    asciiToArray,
    BaseStemmer,
    Clonable,
    compareWildcars,
    Container,
    containerBootstrap,
    Context,
    defaultContainer,
    dock,
    dockStart,
    getAbsolutePath,
    hasUnicode,
    listFiles,
    listFilesAbsolute,
    loadEnv,
    MemoryStorage,
    Normalizer,
    ObjToArr,
    Stemmer,
    Stopwords,
    stringToArray,
    Timer,
    Tokenizer,
    unicodeToArray,
    uuid,
  } from '@nlpjs/core-loader'
  import { compile, Evaluator, JavascriptCompiler, Template } from '@nlpjs/evaluator'
  import { LangEn, NormalizerEn, SentimentEn, StemmerEn, StopwordsEn, TokenizerEn } from '@nlpjs/lang-en'
  import { logger } from '@nlpjs/logger'
  import { Nlp } from '@nlpjs/nlp'

  export {
    ConsoleConnector,
    Among,
    ArrToObj,
    BaseStemmer,
    containerBootstrap,
    Clonable,
    Container,
    defaultContainer,
    hasUnicode,
    unicodeToArray,
    asciiToArray,
    stringToArray,
    compareWildcars,
    getAbsolutePath,
    listFiles,
    listFilesAbsolute,
    loadEnv,
    Normalizer,
    ObjToArr,
    Stemmer,
    Stopwords,
    Tokenizer,
    Timer,
    MemoryStorage,
    uuid,
    dock,
    Context,
    dockStart,
    Evaluator,
    compile,
    Template,
    JavascriptCompiler,
    LangEn,
    StemmerEn,
    StopwordsEn,
    TokenizerEn,
    NormalizerEn,
    SentimentEn,
    logger,
    Nlp,
  }
}
